### ISSUE TITLE
"Message Result chan not found" on the 128th request

### ISSUE THREAD

**Issue by rsperl** [mmitton/ldap#17]
I have a strange error - I have a few hundred queries to run, each only differing in the basedn used. Every time I run the app, the 128th query fails with the same message:

```
Sending message 128
Receiving message 4294967168
Message Result chan not found (possible Abandon), MessageID: 4294967168
```

Every message before this succeeds, and I can confirm by seeing 

```
MessageID: 127, ok: true
...
Sending message 127
Receiving message 127
...
```

I'm happy to send more information if needed, but does this give you any idea why the 128th query fails?

**Comment by excilsploft** [comment]
I believe this has to do with a bad cast but I am dealing with the same issue only in the mavricknz/ldap version of this. It is actually down in the asn1.ber library
